# # Use Node.js base image with a specified version
# FROM node:16.14.0-alpine as build

# # Set working directory inside the container
# WORKDIR /app

# # Copy package.json and package-lock.json to container
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the application code to container
# COPY . .

# # Build the application for production
# RUN npm run build

# # Stage 2: Serve with Node.js server
# FROM node:16.14.0-alpine

# # Set working directory inside the container
# WORKDIR /app

# # Copy the built app from previous stage
# COPY --from=build /app/dist ./dist

# # Expose port 3000
# EXPOSE 3000

# # Command to run the application
# CMD ["node", "./dist/server.js"]

FROM node:18-alpine

WORKDIR /app

COPY package.json .

RUN npm install

RUN npm i -g serve

COPY . .

RUN npm run build

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]