version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  backend:
    build: ./user-management-service
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/userdb
    depends_on:
      - mongo
